### ISSUE TITLE
rubocopの設定を検討する

### ISSUE THREAD

**Issue by Kassy0220** [Kassy0220/fjord-minutes#51]
現在、Railsにデフォルトで入っている[rubocop-rails-omakase](https://github.com/rails/rubocop-rails-omakase)の設定を使っている。

rubocop-rails-omakaseには以下の設定があり、一旦すべてのcopをdisabledにしている。
この設定により、`Style/FrozenStringLiteralComment`などもdisabledとなっていた。

```yaml
AllCops:
  SuggestExtensions: false
  DisabledByDefault: true
```

このrubocop-rails-omakaseの設定が妥当なものか検討を行う。
